on:
  pull_request:
    types: [closed]
    branches: [main]
  push:
    branches: [main]   # optional but handy
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without committing changes"
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: read

jobs:
  update:
    # For PR trigger: only when merged; for manual/push: only when on main
    if: >
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
      || (github.event_name != 'pull_request' && startsWith(github.ref, 'refs/heads/main'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build README section
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run update-readme

      - name: Commit & push if changed
        if: ${{ !inputs.dry_run }}
        run: |
          if ! git diff --quiet -- README.md .idea_attribution.json; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md .idea_attribution.json
            git commit -m "chore: update ideas list [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
